
async function  fetchData(){
    let options={"method":"GET"}
    let response=await fetch("https://cdn.shopify.com/s/files/1/0564/3685/0790/files/singleProduct.json?v=1701948448",options)
    let data=await response.json()
    console.log(data.product)

    let flexContainer=document.getElementById("flexContainer")
    let imgContainer=document.createElement("div")
    flexContainer.appendChild(imgContainer)
    imgContainer.classList.add("img-container")
    let imageElement=document.createElement("img")
    imgContainer.appendChild(imageElement)
    imageElement.setAttribute("src","https://i.postimg.cc/nLJg47S3/Sexy-algod-o-curto-feminino-camisa-branca-sexy-bot-o-de.webp")
    imageElement.classList.add("img-element")
    imageElement.setAttribute("alt","altText")
    let thumbnailsContainer=document.createElement("div")
    imgContainer.appendChild(thumbnailsContainer)
    let thumbnail1=document.createElement("img")
    thumbnailsContainer.appendChild(thumbnail1)
    thumbnail1.src="https://i.postimg.cc/nLJg47S3/Sexy-algod-o-curto-feminino-camisa-branca-sexy-bot-o-de.webp"
    thumbnail1.classList.add("thumbnails-2")
    thumbnailsContainer.classList.add("thumbnails")
    let thumbnail2=document.createElement("img")
    thumbnailsContainer.appendChild(thumbnail2)
    thumbnail2.src="https://i.postimg.cc/nLJg47S3/Sexy-algod-o-curto-feminino-camisa-branca-sexy-bot-o-de.webp"
    thumbnail2.classList.add("thumbnails-1")
    thumbnail2.addEventListener("click",function(){
        thumbnail2.classList.remove("thumbnails-1")
        thumbnail2.classList.add("thumbnails-2")
        thumbnail1.classList.remove("thumbnails-2")
        thumbnail1.classList.add("thumbnails-1")
        thumbnail3.classList.remove("thumbnails-2")
        thumbnail3.classList.add("thumbnails-1")
        thumbnail4.classList.remove("thumbnails-2")
        thumbnail4.classList.add("thumbnails-1")
    })
    thumbnail1.addEventListener("click",function(){
        thumbnail2.classList.remove("thumbnails-2")
        thumbnail2.classList.add("thumbnails-1")
        thumbnail1.classList.remove("thumbnails-1")
        thumbnail1.classList.add("thumbnails-2")
        thumbnail3.classList.remove("thumbnails-2")
        thumbnail3.classList.add("thumbnails-1")
        thumbnail4.classList.remove("thumbnails-2")
        thumbnail4.classList.add("thumbnails-1")
    })
    thumbnailsContainer.classList.add("thumbnails")
    let thumbnail3=document.createElement("img")
    thumbnailsContainer.appendChild(thumbnail3)
    thumbnail3.src="https://i.postimg.cc/nLJg47S3/Sexy-algod-o-curto-feminino-camisa-branca-sexy-bot-o-de.webp"
    thumbnail3.classList.add("thumbnails-1")
    thumbnailsContainer.classList.add("thumbnails")
    thumbnail3.addEventListener("click",function(){
        thumbnail2.classList.remove("thumbnails-2")
        thumbnail2.classList.add("thumbnails-1")
        thumbnail1.classList.remove("thumbnails-2")
        thumbnail1.classList.add("thumbnails-1")
        thumbnail3.classList.remove("thumbnails-1")
        thumbnail3.classList.add("thumbnails-2")
        thumbnail4.classList.remove("thumbnails-2")
        thumbnail4.classList.add("thumbnails-1")
    })
    let thumbnail4=document.createElement("img")
    thumbnailsContainer.appendChild(thumbnail4)
    thumbnail4.src="https://i.postimg.cc/nLJg47S3/Sexy-algod-o-curto-feminino-camisa-branca-sexy-bot-o-de.webp"
    thumbnail4.classList.add("thumbnails-1")
    thumbnail4.addEventListener("click",function(){
        thumbnail2.classList.remove("thumbnails-2")
        thumbnail2.classList.add("thumbnails-1")
        thumbnail1.classList.remove("thumbnails-2")
        thumbnail1.classList.add("thumbnails-1")
        thumbnail3.classList.remove("thumbnails-2")
        thumbnail3.classList.add("thumbnails-1")
        thumbnail4.classList.remove("thumbnails-1")
        thumbnail4.classList.add("thumbnails-2")
    })
    thumbnailsContainer.classList.add("thumbnails")
    let contentContainer=document.createElement("div")
    flexContainer.appendChild(contentContainer)
    contentContainer.classList.add("content-container")
    let paragraphEl=document.createElement("h1")
    contentContainer.appendChild(paragraphEl)
    paragraphEl.textContent=data.product.vendor
    paragraphEl.classList.add("paragraph-el")
    paragraphEl.classList.add("para-element")
    let titleEl=document.createElement("p")
    contentContainer.appendChild(titleEl)
    titleEl.textContent=data.product.title
    titleEl.classList.add("title-el")
    let moneyContainer=document.createElement("div")
    contentContainer.appendChild(moneyContainer)
    moneyContainer.classList.add("money-container")
    let price=document.createElement("p")
    price.classList.add("price")
    moneyContainer.appendChild(price)
    price.textContent=data.product.price+".00"
    let percent=document.createElement("p")
    moneyContainer.appendChild(percent)
    percent.textContent="35% Off"
    percent.classList.add("percent")
    let compareValue=document.createElement("p")
    contentContainer.appendChild(compareValue)
    compareValue.textContent=data.product.compare_at_price+".00"
    compareValue.classList.add("compare-value")
    let chooseColor=document.createElement("p")
    contentContainer.appendChild(chooseColor)
    chooseColor.textContent="Choose Color"
    chooseColor.classList.add("choose-size")
    let colorsContainer=document.createElement("div")
    contentContainer.appendChild(colorsContainer)
    colorsContainer.classList.add("colorsContainer")
    let orangeColor=document.createElement("div")
    colorsContainer.appendChild(orangeColor)
    orangeColor.classList.add("orange_main")
    orangeColor.addEventListener("click",function(){
        orangeColor.classList.remove("orange")
        orangeColor.classList.add("orange_main")
        greenColor.classList.remove("green_main")
        greenColor.classList.add("green")
        blueColor.classList.remove("blue_main")
        blueColor.classList.add("blue")
        pinkColor.classList.remove("pink_main")
        pinkColor.classList.add("pink")
    })
    let greenColor=document.createElement("div")
    colorsContainer.appendChild(greenColor)
    greenColor.classList.add("green")
    greenColor.addEventListener("click",function(){
        orangeColor.classList.remove("orange_main")
        orangeColor.classList.add("orange")
        greenColor.classList.remove("green")
        greenColor.classList.add("green_main")
        blueColor.classList.remove("blue_main")
        blueColor.classList.add("blue")
        pinkColor.classList.remove("pink_main")
        pinkColor.classList.add("pink")
    })
    let blueColor=document.createElement("div")
    colorsContainer.appendChild(blueColor)
    blueColor.classList.add("blue")
    blueColor.addEventListener("click",function(){
        orangeColor.classList.remove("orange_main")
        orangeColor.classList.add("orange")
        greenColor.classList.remove("green_main")
        greenColor.classList.add("green")
        blueColor.classList.remove("blue")
        blueColor.classList.add("blue_main")
        pinkColor.classList.remove("pink_main")
        pinkColor.classList.add("pink")
    })
    let pinkColor=document.createElement("div")
    colorsContainer.appendChild(pinkColor)
    pinkColor.classList.add("pink")
    pinkColor.addEventListener("click",function(){
        orangeColor.classList.remove("orange_main")
        orangeColor.classList.add("orange")
        greenColor.classList.remove("green_main")
        greenColor.classList.add("green")
        blueColor.classList.remove("blue_main")
        blueColor.classList.add("blue")
        pinkColor.classList.remove("pink")
        pinkColor.classList.add("pink_main")
    })
    let chooseSize=document.createElement("p")
    contentContainer.appendChild(chooseSize)
    chooseSize.textContent="Choose Size"
    chooseSize.classList.add("choose-size")
    let sizeContainer=document.createElement("div")
    contentContainer.appendChild(sizeContainer)
    sizeContainer.classList.add("sizeContainer")
    let smallContainer=document.createElement("div")
    sizeContainer.appendChild(smallContainer)
    smallContainer.classList.add("smallcontainer")
    let small=document.createElement("input")
    smallContainer.appendChild(small)
    small.setAttribute("type","radio")
    small.setAttribute("name","size")
    small.classList.add("required") 
    let label=document.createElement("p")
    label.classList.add("labelEl")
    smallContainer.appendChild(label)
    label.textContent="small"
    let mediumContainer=document.createElement("div")
    sizeContainer.appendChild(mediumContainer)
    mediumContainer.classList.add("mediumcontainer")
    let medium=document.createElement("input")
    mediumContainer.appendChild(medium)
    medium.setAttribute("type","radio")
    medium.setAttribute("name","size")
    let labelM=document.createElement("p")
    mediumContainer.appendChild(labelM)
    labelM.classList.add("labelEl")
    labelM.textContent="medium"
    let largeContainer=document.createElement("div")
    sizeContainer.appendChild(largeContainer)
    largeContainer.classList.add("largeContainer")
    let large=document.createElement("input")
    largeContainer.appendChild(large)
    large.setAttribute("type","radio")
    large.setAttribute("name","size")
    let labelL=document.createElement("p")
    largeContainer.appendChild(labelL)
    labelL.classList.add("labelEl")
    labelL.textContent="large"
    let extralargeContainer=document.createElement("div")
    sizeContainer.appendChild(extralargeContainer)
    extralargeContainer.classList.add("extraLarge")
    let extraLarge=document.createElement("input")
    extralargeContainer.appendChild(extraLarge)
    extraLarge.setAttribute("type","radio")
    extraLarge.setAttribute("name","size")
    let labelLL=document.createElement("p")
    extralargeContainer.appendChild(labelLL)
    labelLL.classList.add("labelEl")
    labelLL.textContent="XXL"
    let buttonsContainer=document.createElement("div")
    contentContainer.appendChild(buttonsContainer)
    buttonsContainer.classList.add("buttonsContainer")
    let plusOrminus=document.createElement("div")
    buttonsContainer.appendChild(plusOrminus)
    plusOrminus.classList.add("plusOrminus")
    let minus=document.createElement("button")
    plusOrminus.appendChild(minus)
    minus.textContent="-"
    minus.classList.add("plus")
    let paraCount=document.createElement("h1")
    plusOrminus.appendChild(paraCount)
    paraCount.textContent="1"
    paraCount.classList.add("paracount")
    let plus=document.createElement("button")
    plusOrminus.appendChild(plus)
    plus.textContent="+"
    plus.classList.add("plus")
    let  count=1
    plus.addEventListener("click",function(){
        paraCount.textContent=count+1
        count=count+1
    })
    minus.addEventListener("click",function(){
        if (paraCount.textContent>=1){
            paraCount.textContent=count-1
            count=count-1

        }
    })
    let cartContainer=document.createElement("button")
    buttonsContainer.appendChild(cartContainer)
    cartContainer.classList.add("cartContainer")
    let cartImg=document.createElement("img")
    cartContainer.appendChild(cartImg)
    cartImg.src="https://i.postimg.cc/J7JYg34Q/Pngtree-shopping-cart-icon-4436010.png"
    cartImg.setAttribute("alt","caartImg")
    cartImg.classList.add("cart-img")
    let cartText=document.createElement("h1")
    cartContainer.appendChild(cartText)
    cartText.textContent="Add To Cart"
    cartText.classList.add("cart-text")
    let cartAddedItem=document.createElement("p")
    contentContainer.appendChild(cartAddedItem)
    cartContainer.addEventListener("click",function(){
        cartAddedItem.textContent="Embrace Sideboard with color Yellow and size small is added to cart"
        cartAddedItem.classList.add("cartaddeditem")
    })
    let description=document.createElement("p")
    contentContainer.appendChild(description)
    description.textContent=data.product.description
    description.classList.add("description")

}
fetchData()





